### ISSUE TITLE
Scraper unit tests fail due to time-zone code

### ISSUE THREAD

**Issue by scjohnson16** [ahampe/KDVS#69]
```
Caused by: org.threeten.bp.zone.ZoneRulesException: No time-zone data files registered
	at org.threeten.bp.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:165)
	at org.threeten.bp.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:122)
	at org.threeten.bp.ZoneRegion.ofId(ZoneRegion.java:143)
	at org.threeten.bp.ZoneId.of(ZoneId.java:358)
	at fho.kdvs.global.util.TimeHelper.<clinit>(TimeHelper.kt:27)
	... 25 more
```
~~I tried the solution described [here](https://stackoverflow.com/a/53085180/9661059), but this raises a NullPointerException when invoking `ZonedDateTime` methods.~~

The whole problem stems from the fact that ZonedDateTime involves Android system methods whereas Robolectric runs on JVM.

**Comment by scjohnson16** [comment]
Managed to clear up the ZoneRules unit test issue by following the guide here: https://pbochenski.pl/blog/04-14-2017-testing-three-ten-abp.html

Still getting null exceptions, but it looks like these are stemming from a setter method on `KdvsPreferences.lastNewsScrape` and not the time libraries.
